export const DETAIL_CARTE_HTML_TEXTE = {
  TYPE: "TYPE",
  SUB_TYPE: 'SOUS-TYPE',
  ATTRIBUTS: "ATTRIBUTS",
  MAIN_EFFECT: "EFFET PRINCIPAL",
  ECHO_EFFECT: "EFFET DE RESERVE",
  RARITY: "Rareté",
  SETS: "Édition",
  VARIANTES: "Cartes Altérées",
  INFORMATIONS: "Informations"
};